FROM mcr.microsoft.com/dotnet/aspnet:9.0

EXPOSE ${ASPNETCORE_HTTP_PORTS}

RUN apt -y update && apt -y install curl
COPY /_immense.CoreConnect/Server/linux-x64/Server /app

WORKDIR /app

ENTRYPOINT ["dotnet", "CoreConnect_Server.dll"]

HEALTHCHECK \
  CMD curl -f http://localhost:${ASPNETCORE_HTTP_PORTS}/api/healthcheck || exit 1