name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: CoreConnect.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --no-build --configuration ${{ matrix.configuration }} --verbosity normal
